name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - prod

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Build Tailwind and Templ
        run: make build
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Project to vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}